global using ApiBestPracticesExample.Contracts.Requests;
global using ApiBestPracticesExample.Contracts.Responses;
global using ApiBestPracticesExample.Infrastructure.Database;
global using FastEndpoints;
global using FastEndpoints.Security;
global using FastEndpoints.Testing;
global using FluentAssertions;
global using Xunit;
global using Xunit.Abstractions;