// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using ApiBestPracticesExample.Domain.Entities;

namespace ApiBestPracticesExample.Infrastructure.Database
{
    public partial class AppDbContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
