version: '3.4'

services:
  apibestpracticesexample.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__SqlConnection=Data Source=sqlserver; Database=testDb;User Id=sa;Password=Qwerty123$;TrustServerCertificate=True
      - ConnectionStrings_RedisConnection=redis
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sqlserver:
    environment:
      SA_PASSWORD: "Qwerty123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Qwerty123$ -Q 'SELECT 1;'"
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    ports:
      - "6379:6379"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5