version: '3.4'

services:
  apibestpracticesexample.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__SqlConnection=Server=sqlserver;Database=ApiBestPracticesExample;User=sa;Password=Qwerty123$;TrustServerCertificate=True
      - ConnectionStrings__RedisConnection=redis
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  sqlserver:
    environment:
      SA_PASSWORD: "Qwerty123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Qwerty123$ -Q 'SELECT 1;'"
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    ports:
      - "6379:6379"
    healthcheck:
      test: "redis-cli ping"
      interval: 10s
      timeout: 5s
      retries: 5